### ISSUE TITLE
TODO/FIXME Count 6

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-passport#39]
- [ ] FIXME: consider not running this automatically (breaking change)
       Commit: (918b404) Simplify API; use promises.
       File:  [lib/index.js:389](https://github.com/digitalbazaar/bedrock-passport/blob/master/lib/index.js#L389)
       Dave Longley commented 2 years ago

  - [ ] TODO: which `identity`? it is possible to authenticate as multiple, so
       Commit: (918b404) Simplify API; use promises.
       File:  [lib/index.js:251](https://github.com/digitalbazaar/bedrock-passport/blob/master/lib/index.js#L251)
       Dave Longley commented 2 years ago

  - [ ] TODO: may want to allow users to authenticate as multiple accounts when
       Commit: (918b404) Simplify API; use promises.
       File:  [lib/index.js:209](https://github.com/digitalbazaar/bedrock-passport/blob/master/lib/index.js#L209)
       Dave Longley commented 2 years ago

  - [ ] FIXME: `req.isAuthenticated` is not technically granular enough
       Commit: (918b404) Simplify API; use promises.
       File:  [lib/index.js:96](https://github.com/digitalbazaar/bedrock-passport/blob/master/lib/index.js#L96)
       Dave Longley commented 2 years ago

  - [ ] TODO: potentially refactor to avoid this auto-check in the future,
       Commit: (918b404) Simplify API; use promises.
       File:  [lib/index.js:94](https://github.com/digitalbazaar/bedrock-passport/blob/master/lib/index.js#L94)
       Dave Longley commented 2 years ago

  - [ ] TODO: add an option to allow controlling permittedCorsMethods for
       Commit: (918b404) Simplify API; use promises.
       File:  [lib/index.js:82](https://github.com/digitalbazaar/bedrock-passport/blob/master/lib/index.js#L82)
       Dave Longley commented 2 years ago
